[theme]
primaryColor = "blue"
backgroundColor = "#181818"  # Dark background
secondaryBackgroundColor = "#262730"  # Slightly lighter for secondary elements
textColor = "#ffffff"  # White text
font = "sans serif"